language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-19.1.0
    - android-19
    - sys-img-armeabi-v7a-android-19
    - extra-android-support
    - extra-android-m2repository
before_install:
  - mkdir -p ~/.m2/repository
  - cp -R $ANDROID_HOME/extras/android/m2repository/com ~/.m2/repository
install:
  - mvn clean install -DskipTests=true -pl openxc -am
before_script:
  - echo no | android create avd --force -n test -c 128M -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - ./wait_for_emulator
script:
  - mvn test -pl openxc
  - mvn install -pl openxc-it
  - mvn package -pl enabler
after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura -pl openxc
