language: android
android:
  components:
    - platform-tools
    - android-19
    - sysimg-19
    - build-tools-19.0.1
    - extra-android-support
    - extra-android-m2repository
before_install:
  - cp -R $ANDROID_HOME/extras/android/m2repository/com ~/.m2/repository
install:
  - mvn clean install -DskipTests=true -pl openxc -am
script:
  - mvn test -pl openxc
  - mvn test -pl openxc-it
  - mvn package -pl enabler
